// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eng_cheat;

namespace eng_cheat.Migrations
{
    [DbContext(typeof(VerbContext))]
    partial class VerbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("eng_cheat.Verb", b =>
                {
                    b.Property<int>("VerbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Infinitive")
                        .HasColumnType("TEXT");

                    b.Property<string>("Participle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Simple")
                        .HasColumnType("TEXT");

                    b.HasKey("VerbId");

                    b.ToTable("Verbs");
                });
#pragma warning restore 612, 618
        }
    }
}
